CREATE TABLE IF NOT EXISTS roles (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

ALTER TABLE users ADD COLUMN role_Id BIGINT;

ALTER TABLE users ADD CONSTRAINT fk_users_roles FOREIGN KEY (role_Id) REFERENCES roles(id);
