// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/aasumitro/posbe/domain"
	mock "github.com/stretchr/testify/mock"

	utils "github.com/aasumitro/posbe/pkg/utils"
)

// ICatalogProductService is an autogenerated mock type for the ICatalogProductService type
type ICatalogProductService struct {
	mock.Mock
}

// AddProductVariant provides a mock function with given fields: data
func (_m *ICatalogProductService) AddProductVariant(data *domain.ProductVariant) (*domain.ProductVariant, *utils.ServiceError) {
	ret := _m.Called(data)

	var r0 *domain.ProductVariant
	if rf, ok := ret.Get(0).(func(*domain.ProductVariant) *domain.ProductVariant); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductVariant)
		}
	}

	var r1 *utils.ServiceError
	if rf, ok := ret.Get(1).(func(*domain.ProductVariant) *utils.ServiceError); ok {
		r1 = rf(data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}

	return r0, r1
}

// DeleteProductVariant provides a mock function with given fields: data
func (_m *ICatalogProductService) DeleteProductVariant(data *domain.ProductVariant) *utils.ServiceError {
	ret := _m.Called(data)

	var r0 *utils.ServiceError
	if rf, ok := ret.Get(0).(func(*domain.ProductVariant) *utils.ServiceError); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.ServiceError)
		}
	}

	return r0
}

// EditProductVariant provides a mock function with given fields: data
func (_m *ICatalogProductService) EditProductVariant(data *domain.ProductVariant) (*domain.ProductVariant, *utils.ServiceError) {
	ret := _m.Called(data)

	var r0 *domain.ProductVariant
	if rf, ok := ret.Get(0).(func(*domain.ProductVariant) *domain.ProductVariant); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductVariant)
		}
	}

	var r1 *utils.ServiceError
	if rf, ok := ret.Get(1).(func(*domain.ProductVariant) *utils.ServiceError); ok {
		r1 = rf(data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewICatalogProductService interface {
	mock.TestingT
	Cleanup(func())
}

// NewICatalogProductService creates a new instance of ICatalogProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewICatalogProductService(t mockConstructorTestingTNewICatalogProductService) *ICatalogProductService {
	mock := &ICatalogProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
