version: "2"
run:
  go: "1.26"
  modules-download-mode: readonly
linters:
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 800
    gosec:
      excludes:
        - G404
        - G101
    lll:
      line-length: 450
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - govet
          - lll
          - mnd
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$