// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aasumitro/posbe/internal/account"
	"github.com/aasumitro/posbe/internal/model"
	"github.com/aasumitro/posbe/internal/utils"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIAccountRepository creates a new instance of MockIAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAccountRepository {
	mock := &MockIAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAccountRepository is an autogenerated mock type for the IAccountRepository type
type MockIAccountRepository struct {
	mock.Mock
}

type MockIAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAccountRepository) EXPECT() *MockIAccountRepository_Expecter {
	return &MockIAccountRepository_Expecter{mock: &_m.Mock}
}

// DeleteUserByID provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) DeleteUserByID(ctx context.Context, user model.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccountRepository_DeleteUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByID'
type MockIAccountRepository_DeleteUserByID_Call struct {
	*mock.Call
}

// DeleteUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *MockIAccountRepository_Expecter) DeleteUserByID(ctx interface{}, user interface{}) *MockIAccountRepository_DeleteUserByID_Call {
	return &MockIAccountRepository_DeleteUserByID_Call{Call: _e.mock.On("DeleteUserByID", ctx, user)}
}

func (_c *MockIAccountRepository_DeleteUserByID_Call) Run(run func(ctx context.Context, user model.User)) *MockIAccountRepository_DeleteUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_DeleteUserByID_Call) Return(err error) *MockIAccountRepository_DeleteUserByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccountRepository_DeleteUserByID_Call) RunAndReturn(run func(ctx context.Context, user model.User) error) *MockIAccountRepository_DeleteUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserBy provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) FindUserBy(ctx context.Context, key model.FindWith, val any) (*model.User, error) {
	ret := _mock.Called(ctx, key, val)

	if len(ret) == 0 {
		panic("no return value specified for FindUserBy")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindWith, any) (*model.User, error)); ok {
		return returnFunc(ctx, key, val)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindWith, any) *model.User); ok {
		r0 = returnFunc(ctx, key, val)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.FindWith, any) error); ok {
		r1 = returnFunc(ctx, key, val)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountRepository_FindUserBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserBy'
type MockIAccountRepository_FindUserBy_Call struct {
	*mock.Call
}

// FindUserBy is a helper method to define mock.On call
//   - ctx context.Context
//   - key model.FindWith
//   - val any
func (_e *MockIAccountRepository_Expecter) FindUserBy(ctx interface{}, key interface{}, val interface{}) *MockIAccountRepository_FindUserBy_Call {
	return &MockIAccountRepository_FindUserBy_Call{Call: _e.mock.On("FindUserBy", ctx, key, val)}
}

func (_c *MockIAccountRepository_FindUserBy_Call) Run(run func(ctx context.Context, key model.FindWith, val any)) *MockIAccountRepository_FindUserBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.FindWith
		if args[1] != nil {
			arg1 = args[1].(model.FindWith)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_FindUserBy_Call) Return(user *model.User, err error) *MockIAccountRepository_FindUserBy_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIAccountRepository_FindUserBy_Call) RunAndReturn(run func(ctx context.Context, key model.FindWith, val any) (*model.User, error)) *MockIAccountRepository_FindUserBy_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRoles provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) GetAllRoles(ctx context.Context) ([]*model.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRoles")
	}

	var r0 []*model.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountRepository_GetAllRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRoles'
type MockIAccountRepository_GetAllRoles_Call struct {
	*mock.Call
}

// GetAllRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAccountRepository_Expecter) GetAllRoles(ctx interface{}) *MockIAccountRepository_GetAllRoles_Call {
	return &MockIAccountRepository_GetAllRoles_Call{Call: _e.mock.On("GetAllRoles", ctx)}
}

func (_c *MockIAccountRepository_GetAllRoles_Call) Run(run func(ctx context.Context)) *MockIAccountRepository_GetAllRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_GetAllRoles_Call) Return(roles []*model.Role, err error) *MockIAccountRepository_GetAllRoles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockIAccountRepository_GetAllRoles_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Role, error)) *MockIAccountRepository_GetAllRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) GetAllUsers(ctx context.Context) ([]*model.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountRepository_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockIAccountRepository_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAccountRepository_Expecter) GetAllUsers(ctx interface{}) *MockIAccountRepository_GetAllUsers_Call {
	return &MockIAccountRepository_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *MockIAccountRepository_GetAllUsers_Call) Run(run func(ctx context.Context)) *MockIAccountRepository_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_GetAllUsers_Call) Return(users []*model.User, err error) *MockIAccountRepository_GetAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockIAccountRepository_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context) ([]*model.User, error)) *MockIAccountRepository_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) InsertUser(ctx context.Context, user model.User) (*model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (*model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) *model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountRepository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type MockIAccountRepository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *MockIAccountRepository_Expecter) InsertUser(ctx interface{}, user interface{}) *MockIAccountRepository_InsertUser_Call {
	return &MockIAccountRepository_InsertUser_Call{Call: _e.mock.On("InsertUser", ctx, user)}
}

func (_c *MockIAccountRepository_InsertUser_Call) Run(run func(ctx context.Context, user model.User)) *MockIAccountRepository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_InsertUser_Call) Return(user1 *model.User, err error) *MockIAccountRepository_InsertUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockIAccountRepository_InsertUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) (*model.User, error)) *MockIAccountRepository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserByID provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) UpdateUserByID(ctx context.Context, user model.User) (*model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (*model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) *model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountRepository_UpdateUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserByID'
type MockIAccountRepository_UpdateUserByID_Call struct {
	*mock.Call
}

// UpdateUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *MockIAccountRepository_Expecter) UpdateUserByID(ctx interface{}, user interface{}) *MockIAccountRepository_UpdateUserByID_Call {
	return &MockIAccountRepository_UpdateUserByID_Call{Call: _e.mock.On("UpdateUserByID", ctx, user)}
}

func (_c *MockIAccountRepository_UpdateUserByID_Call) Run(run func(ctx context.Context, user model.User)) *MockIAccountRepository_UpdateUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_UpdateUserByID_Call) Return(user1 *model.User, err error) *MockIAccountRepository_UpdateUserByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockIAccountRepository_UpdateUserByID_Call) RunAndReturn(run func(ctx context.Context, user model.User) (*model.User, error)) *MockIAccountRepository_UpdateUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAccountService creates a new instance of MockIAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAccountService {
	mock := &MockIAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAccountService is an autogenerated mock type for the IAccountService type
type MockIAccountService struct {
	mock.Mock
}

type MockIAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAccountService) EXPECT() *MockIAccountService_Expecter {
	return &MockIAccountService_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) AuthenticateUser(ctx context.Context, form *account.LoginForm) (*model.User, *utils.ServiceError) {
	ret := _mock.Called(ctx, form)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 *model.User
	var r1 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.LoginForm) (*model.User, *utils.ServiceError)); ok {
		return returnFunc(ctx, form)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.LoginForm) *model.User); ok {
		r0 = returnFunc(ctx, form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *account.LoginForm) *utils.ServiceError); ok {
		r1 = returnFunc(ctx, form)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}
	return r0, r1
}

// MockIAccountService_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type MockIAccountService_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - form *account.LoginForm
func (_e *MockIAccountService_Expecter) AuthenticateUser(ctx interface{}, form interface{}) *MockIAccountService_AuthenticateUser_Call {
	return &MockIAccountService_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", ctx, form)}
}

func (_c *MockIAccountService_AuthenticateUser_Call) Run(run func(ctx context.Context, form *account.LoginForm)) *MockIAccountService_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.LoginForm
		if args[1] != nil {
			arg1 = args[1].(*account.LoginForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountService_AuthenticateUser_Call) Return(user *model.User, serviceError *utils.ServiceError) *MockIAccountService_AuthenticateUser_Call {
	_c.Call.Return(user, serviceError)
	return _c
}

func (_c *MockIAccountService_AuthenticateUser_Call) RunAndReturn(run func(ctx context.Context, form *account.LoginForm) (*model.User, *utils.ServiceError)) *MockIAccountService_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) CreateUser(ctx context.Context, data *account.NewUserForm) (*model.User, *utils.ServiceError) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.NewUserForm) (*model.User, *utils.ServiceError)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.NewUserForm) *model.User); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *account.NewUserForm) *utils.ServiceError); ok {
		r1 = returnFunc(ctx, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}
	return r0, r1
}

// MockIAccountService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIAccountService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data *account.NewUserForm
func (_e *MockIAccountService_Expecter) CreateUser(ctx interface{}, data interface{}) *MockIAccountService_CreateUser_Call {
	return &MockIAccountService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, data)}
}

func (_c *MockIAccountService_CreateUser_Call) Run(run func(ctx context.Context, data *account.NewUserForm)) *MockIAccountService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.NewUserForm
		if args[1] != nil {
			arg1 = args[1].(*account.NewUserForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountService_CreateUser_Call) Return(user *model.User, serviceError *utils.ServiceError) *MockIAccountService_CreateUser_Call {
	_c.Call.Return(user, serviceError)
	return _c
}

func (_c *MockIAccountService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, data *account.NewUserForm) (*model.User, *utils.ServiceError)) *MockIAccountService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) RefreshToken(ctx context.Context, token string) (*model.User, *utils.ServiceError) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *model.User
	var r1 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, *utils.ServiceError)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *utils.ServiceError); ok {
		r1 = returnFunc(ctx, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}
	return r0, r1
}

// MockIAccountService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockIAccountService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockIAccountService_Expecter) RefreshToken(ctx interface{}, token interface{}) *MockIAccountService_RefreshToken_Call {
	return &MockIAccountService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, token)}
}

func (_c *MockIAccountService_RefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockIAccountService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountService_RefreshToken_Call) Return(user *model.User, serviceError *utils.ServiceError) *MockIAccountService_RefreshToken_Call {
	_c.Call.Return(user, serviceError)
	return _c
}

func (_c *MockIAccountService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*model.User, *utils.ServiceError)) *MockIAccountService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUser provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) RemoveUser(ctx context.Context, data *model.User) *utils.ServiceError {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) *utils.ServiceError); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.ServiceError)
		}
	}
	return r0
}

// MockIAccountService_RemoveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUser'
type MockIAccountService_RemoveUser_Call struct {
	*mock.Call
}

// RemoveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data *model.User
func (_e *MockIAccountService_Expecter) RemoveUser(ctx interface{}, data interface{}) *MockIAccountService_RemoveUser_Call {
	return &MockIAccountService_RemoveUser_Call{Call: _e.mock.On("RemoveUser", ctx, data)}
}

func (_c *MockIAccountService_RemoveUser_Call) Run(run func(ctx context.Context, data *model.User)) *MockIAccountService_RemoveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountService_RemoveUser_Call) Return(serviceError *utils.ServiceError) *MockIAccountService_RemoveUser_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *MockIAccountService_RemoveUser_Call) RunAndReturn(run func(ctx context.Context, data *model.User) *utils.ServiceError) *MockIAccountService_RemoveUser_Call {
	_c.Call.Return(run)
	return _c
}

// Roles provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) Roles(ctx context.Context) ([]*model.Role, *utils.ServiceError) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Roles")
	}

	var r0 []*model.Role
	var r1 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Role, *utils.ServiceError)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *utils.ServiceError); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}
	return r0, r1
}

// MockIAccountService_Roles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Roles'
type MockIAccountService_Roles_Call struct {
	*mock.Call
}

// Roles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAccountService_Expecter) Roles(ctx interface{}) *MockIAccountService_Roles_Call {
	return &MockIAccountService_Roles_Call{Call: _e.mock.On("Roles", ctx)}
}

func (_c *MockIAccountService_Roles_Call) Run(run func(ctx context.Context)) *MockIAccountService_Roles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIAccountService_Roles_Call) Return(roles []*model.Role, serviceError *utils.ServiceError) *MockIAccountService_Roles_Call {
	_c.Call.Return(roles, serviceError)
	return _c
}

func (_c *MockIAccountService_Roles_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Role, *utils.ServiceError)) *MockIAccountService_Roles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) UpdateUser(ctx context.Context, data *account.UpdateUserForm) (*model.User, *utils.ServiceError) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *model.User
	var r1 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.UpdateUserForm) (*model.User, *utils.ServiceError)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.UpdateUserForm) *model.User); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *account.UpdateUserForm) *utils.ServiceError); ok {
		r1 = returnFunc(ctx, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}
	return r0, r1
}

// MockIAccountService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockIAccountService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data *account.UpdateUserForm
func (_e *MockIAccountService_Expecter) UpdateUser(ctx interface{}, data interface{}) *MockIAccountService_UpdateUser_Call {
	return &MockIAccountService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, data)}
}

func (_c *MockIAccountService_UpdateUser_Call) Run(run func(ctx context.Context, data *account.UpdateUserForm)) *MockIAccountService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.UpdateUserForm
		if args[1] != nil {
			arg1 = args[1].(*account.UpdateUserForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountService_UpdateUser_Call) Return(user *model.User, serviceError *utils.ServiceError) *MockIAccountService_UpdateUser_Call {
	_c.Call.Return(user, serviceError)
	return _c
}

func (_c *MockIAccountService_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, data *account.UpdateUserForm) (*model.User, *utils.ServiceError)) *MockIAccountService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) UpdateUserPassword(ctx context.Context, data *account.UpdatePasswordForm) *utils.ServiceError {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.UpdatePasswordForm) *utils.ServiceError); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.ServiceError)
		}
	}
	return r0
}

// MockIAccountService_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type MockIAccountService_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - data *account.UpdatePasswordForm
func (_e *MockIAccountService_Expecter) UpdateUserPassword(ctx interface{}, data interface{}) *MockIAccountService_UpdateUserPassword_Call {
	return &MockIAccountService_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, data)}
}

func (_c *MockIAccountService_UpdateUserPassword_Call) Run(run func(ctx context.Context, data *account.UpdatePasswordForm)) *MockIAccountService_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.UpdatePasswordForm
		if args[1] != nil {
			arg1 = args[1].(*account.UpdatePasswordForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountService_UpdateUserPassword_Call) Return(serviceError *utils.ServiceError) *MockIAccountService_UpdateUserPassword_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *MockIAccountService_UpdateUserPassword_Call) RunAndReturn(run func(ctx context.Context, data *account.UpdatePasswordForm) *utils.ServiceError) *MockIAccountService_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UserByID provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) UserByID(ctx context.Context, id int) (*model.User, *utils.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserByID")
	}

	var r0 *model.User
	var r1 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*model.User, *utils.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) *utils.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}
	return r0, r1
}

// MockIAccountService_UserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByID'
type MockIAccountService_UserByID_Call struct {
	*mock.Call
}

// UserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIAccountService_Expecter) UserByID(ctx interface{}, id interface{}) *MockIAccountService_UserByID_Call {
	return &MockIAccountService_UserByID_Call{Call: _e.mock.On("UserByID", ctx, id)}
}

func (_c *MockIAccountService_UserByID_Call) Run(run func(ctx context.Context, id int)) *MockIAccountService_UserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountService_UserByID_Call) Return(user *model.User, serviceError *utils.ServiceError) *MockIAccountService_UserByID_Call {
	_c.Call.Return(user, serviceError)
	return _c
}

func (_c *MockIAccountService_UserByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*model.User, *utils.ServiceError)) *MockIAccountService_UserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Users provides a mock function for the type MockIAccountService
func (_mock *MockIAccountService) Users(ctx context.Context) ([]*model.User, *utils.ServiceError) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 []*model.User
	var r1 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.User, *utils.ServiceError)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *utils.ServiceError); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}
	return r0, r1
}

// MockIAccountService_Users_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Users'
type MockIAccountService_Users_Call struct {
	*mock.Call
}

// Users is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAccountService_Expecter) Users(ctx interface{}) *MockIAccountService_Users_Call {
	return &MockIAccountService_Users_Call{Call: _e.mock.On("Users", ctx)}
}

func (_c *MockIAccountService_Users_Call) Run(run func(ctx context.Context)) *MockIAccountService_Users_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIAccountService_Users_Call) Return(users []*model.User, serviceError *utils.ServiceError) *MockIAccountService_Users_Call {
	_c.Call.Return(users, serviceError)
	return _c
}

func (_c *MockIAccountService_Users_Call) RunAndReturn(run func(ctx context.Context) ([]*model.User, *utils.ServiceError)) *MockIAccountService_Users_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPgxPool creates a new instance of MockIPgxPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPgxPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPgxPool {
	mock := &MockIPgxPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPgxPool is an autogenerated mock type for the IPgxPool type
type MockIPgxPool struct {
	mock.Mock
}

type MockIPgxPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPgxPool) EXPECT() *MockIPgxPool_Expecter {
	return &MockIPgxPool_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockIPgxPool
func (_mock *MockIPgxPool) Exec(context1 context.Context, s string, ifaceVals ...interface{}) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)); ok {
		return returnFunc(context1, s, ifaceVals...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgconn.CommandTag); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(context1, s, ifaceVals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPgxPool_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIPgxPool_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *MockIPgxPool_Expecter) Exec(context1 interface{}, s interface{}, ifaceVals ...interface{}) *MockIPgxPool_Exec_Call {
	return &MockIPgxPool_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *MockIPgxPool_Exec_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *MockIPgxPool_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPgxPool_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockIPgxPool_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockIPgxPool_Exec_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) (pgconn.CommandTag, error)) *MockIPgxPool_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockIPgxPool
func (_mock *MockIPgxPool) Query(context1 context.Context, s string, ifaceVals ...interface{}) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgx.Rows, error)); ok {
		return returnFunc(context1, s, ifaceVals...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Rows); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(context1, s, ifaceVals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPgxPool_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockIPgxPool_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *MockIPgxPool_Expecter) Query(context1 interface{}, s interface{}, ifaceVals ...interface{}) *MockIPgxPool_Query_Call {
	return &MockIPgxPool_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *MockIPgxPool_Query_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *MockIPgxPool_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPgxPool_Query_Call) Return(rows pgx.Rows, err error) *MockIPgxPool_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockIPgxPool_Query_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) (pgx.Rows, error)) *MockIPgxPool_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockIPgxPool
func (_mock *MockIPgxPool) QueryRow(context1 context.Context, s string, ifaceVals ...interface{}) pgx.Row {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// MockIPgxPool_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockIPgxPool_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *MockIPgxPool_Expecter) QueryRow(context1 interface{}, s interface{}, ifaceVals ...interface{}) *MockIPgxPool_QueryRow_Call {
	return &MockIPgxPool_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *MockIPgxPool_QueryRow_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *MockIPgxPool_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIPgxPool_QueryRow_Call) Return(row pgx.Row) *MockIPgxPool_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockIPgxPool_QueryRow_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) pgx.Row) *MockIPgxPool_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
