// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ICatalogProductService is an autogenerated mock type for the ICatalogProductService type
type ICatalogProductService struct {
	mock.Mock
}

type mockConstructorTestingTNewICatalogProductService interface {
	mock.TestingT
	Cleanup(func())
}

// NewICatalogProductService creates a new instance of ICatalogProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewICatalogProductService(t mockConstructorTestingTNewICatalogProductService) *ICatalogProductService {
	mock := &ICatalogProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
