// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mime/multipart"

	"github.com/aasumitro/posbe/internal/utils"
	"github.com/golang-jwt/jwt/v5"
	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIAssetUtil creates a new instance of MockIAssetUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAssetUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAssetUtil {
	mock := &MockIAssetUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAssetUtil is an autogenerated mock type for the IAssetUtil type
type MockIAssetUtil struct {
	mock.Mock
}

type MockIAssetUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAssetUtil) EXPECT() *MockIAssetUtil_Expecter {
	return &MockIAssetUtil_Expecter{mock: &_m.Mock}
}

// DeleteAsset provides a mock function for the type MockIAssetUtil
func (_mock *MockIAssetUtil) DeleteAsset(folder string, name string) error {
	ret := _mock.Called(folder, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(folder, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAssetUtil_DeleteAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAsset'
type MockIAssetUtil_DeleteAsset_Call struct {
	*mock.Call
}

// DeleteAsset is a helper method to define mock.On call
//   - folder string
//   - name string
func (_e *MockIAssetUtil_Expecter) DeleteAsset(folder interface{}, name interface{}) *MockIAssetUtil_DeleteAsset_Call {
	return &MockIAssetUtil_DeleteAsset_Call{Call: _e.mock.On("DeleteAsset", folder, name)}
}

func (_c *MockIAssetUtil_DeleteAsset_Call) Run(run func(folder string, name string)) *MockIAssetUtil_DeleteAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAssetUtil_DeleteAsset_Call) Return(err error) *MockIAssetUtil_DeleteAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAssetUtil_DeleteAsset_Call) RunAndReturn(run func(folder string, name string) error) *MockIAssetUtil_DeleteAsset_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectRootDir provides a mock function for the type MockIAssetUtil
func (_mock *MockIAssetUtil) ProjectRootDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProjectRootDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAssetUtil_ProjectRootDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectRootDir'
type MockIAssetUtil_ProjectRootDir_Call struct {
	*mock.Call
}

// ProjectRootDir is a helper method to define mock.On call
func (_e *MockIAssetUtil_Expecter) ProjectRootDir() *MockIAssetUtil_ProjectRootDir_Call {
	return &MockIAssetUtil_ProjectRootDir_Call{Call: _e.mock.On("ProjectRootDir")}
}

func (_c *MockIAssetUtil_ProjectRootDir_Call) Run(run func()) *MockIAssetUtil_ProjectRootDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIAssetUtil_ProjectRootDir_Call) Return(s string, err error) *MockIAssetUtil_ProjectRootDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIAssetUtil_ProjectRootDir_Call) RunAndReturn(run func() (string, error)) *MockIAssetUtil_ProjectRootDir_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAsset provides a mock function for the type MockIAssetUtil
func (_mock *MockIAssetUtil) UploadAsset(name string, folder string, fileHeader *multipart.FileHeader) (string, error) {
	ret := _mock.Called(name, folder, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for UploadAsset")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *multipart.FileHeader) (string, error)); ok {
		return returnFunc(name, folder, fileHeader)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *multipart.FileHeader) string); ok {
		r0 = returnFunc(name, folder, fileHeader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *multipart.FileHeader) error); ok {
		r1 = returnFunc(name, folder, fileHeader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAssetUtil_UploadAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAsset'
type MockIAssetUtil_UploadAsset_Call struct {
	*mock.Call
}

// UploadAsset is a helper method to define mock.On call
//   - name string
//   - folder string
//   - fileHeader *multipart.FileHeader
func (_e *MockIAssetUtil_Expecter) UploadAsset(name interface{}, folder interface{}, fileHeader interface{}) *MockIAssetUtil_UploadAsset_Call {
	return &MockIAssetUtil_UploadAsset_Call{Call: _e.mock.On("UploadAsset", name, folder, fileHeader)}
}

func (_c *MockIAssetUtil_UploadAsset_Call) Run(run func(name string, folder string, fileHeader *multipart.FileHeader)) *MockIAssetUtil_UploadAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *multipart.FileHeader
		if args[2] != nil {
			arg2 = args[2].(*multipart.FileHeader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAssetUtil_UploadAsset_Call) Return(s string, err error) *MockIAssetUtil_UploadAsset_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIAssetUtil_UploadAsset_Call) RunAndReturn(run func(name string, folder string, fileHeader *multipart.FileHeader) (string, error)) *MockIAssetUtil_UploadAsset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICacheUtil creates a new instance of MockICacheUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICacheUtil[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICacheUtil[T] {
	mock := &MockICacheUtil[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICacheUtil is an autogenerated mock type for the ICacheUtil type
type MockICacheUtil[T any] struct {
	mock.Mock
}

type MockICacheUtil_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockICacheUtil[T]) EXPECT() *MockICacheUtil_Expecter[T] {
	return &MockICacheUtil_Expecter[T]{mock: &_m.Mock}
}

// CacheFirstData provides a mock function for the type MockICacheUtil
func (_mock *MockICacheUtil[T]) CacheFirstData(ctx context.Context, rdp *redis.Client, i *utils.CacheDataSupplied[T]) (T, error) {
	ret := _mock.Called(ctx, rdp, i)

	if len(ret) == 0 {
		panic("no return value specified for CacheFirstData")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *redis.Client, *utils.CacheDataSupplied[T]) (T, error)); ok {
		return returnFunc(ctx, rdp, i)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *redis.Client, *utils.CacheDataSupplied[T]) T); ok {
		r0 = returnFunc(ctx, rdp, i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *redis.Client, *utils.CacheDataSupplied[T]) error); ok {
		r1 = returnFunc(ctx, rdp, i)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICacheUtil_CacheFirstData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheFirstData'
type MockICacheUtil_CacheFirstData_Call[T any] struct {
	*mock.Call
}

// CacheFirstData is a helper method to define mock.On call
//   - ctx context.Context
//   - rdp *redis.Client
//   - i *utils.CacheDataSupplied[T]
func (_e *MockICacheUtil_Expecter[T]) CacheFirstData(ctx interface{}, rdp interface{}, i interface{}) *MockICacheUtil_CacheFirstData_Call[T] {
	return &MockICacheUtil_CacheFirstData_Call[T]{Call: _e.mock.On("CacheFirstData", ctx, rdp, i)}
}

func (_c *MockICacheUtil_CacheFirstData_Call[T]) Run(run func(ctx context.Context, rdp *redis.Client, i *utils.CacheDataSupplied[T])) *MockICacheUtil_CacheFirstData_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *redis.Client
		if args[1] != nil {
			arg1 = args[1].(*redis.Client)
		}
		var arg2 *utils.CacheDataSupplied[T]
		if args[2] != nil {
			arg2 = args[2].(*utils.CacheDataSupplied[T])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockICacheUtil_CacheFirstData_Call[T]) Return(data T, err error) *MockICacheUtil_CacheFirstData_Call[T] {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockICacheUtil_CacheFirstData_Call[T]) RunAndReturn(run func(ctx context.Context, rdp *redis.Client, i *utils.CacheDataSupplied[T]) (T, error)) *MockICacheUtil_CacheFirstData_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockIPasswordUtil creates a new instance of MockIPasswordUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPasswordUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPasswordUtil {
	mock := &MockIPasswordUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPasswordUtil is an autogenerated mock type for the IPasswordUtil type
type MockIPasswordUtil struct {
	mock.Mock
}

type MockIPasswordUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPasswordUtil) EXPECT() *MockIPasswordUtil_Expecter {
	return &MockIPasswordUtil_Expecter{mock: &_m.Mock}
}

// ComparePassword provides a mock function for the type MockIPasswordUtil
func (_mock *MockIPasswordUtil) ComparePassword(par int, stored string, supplied string) (bool, error) {
	ret := _mock.Called(par, stored, supplied)

	if len(ret) == 0 {
		panic("no return value specified for ComparePassword")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string) (bool, error)); ok {
		return returnFunc(par, stored, supplied)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string, string) bool); ok {
		r0 = returnFunc(par, stored, supplied)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = returnFunc(par, stored, supplied)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPasswordUtil_ComparePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePassword'
type MockIPasswordUtil_ComparePassword_Call struct {
	*mock.Call
}

// ComparePassword is a helper method to define mock.On call
//   - par int
//   - stored string
//   - supplied string
func (_e *MockIPasswordUtil_Expecter) ComparePassword(par interface{}, stored interface{}, supplied interface{}) *MockIPasswordUtil_ComparePassword_Call {
	return &MockIPasswordUtil_ComparePassword_Call{Call: _e.mock.On("ComparePassword", par, stored, supplied)}
}

func (_c *MockIPasswordUtil_ComparePassword_Call) Run(run func(par int, stored string, supplied string)) *MockIPasswordUtil_ComparePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPasswordUtil_ComparePassword_Call) Return(b bool, err error) *MockIPasswordUtil_ComparePassword_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIPasswordUtil_ComparePassword_Call) RunAndReturn(run func(par int, stored string, supplied string) (bool, error)) *MockIPasswordUtil_ComparePassword_Call {
	_c.Call.Return(run)
	return _c
}

// MakePassword provides a mock function for the type MockIPasswordUtil
func (_mock *MockIPasswordUtil) MakePassword(par int, supplied string) (string, error) {
	ret := _mock.Called(par, supplied)

	if len(ret) == 0 {
		panic("no return value specified for MakePassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) (string, error)); ok {
		return returnFunc(par, supplied)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) string); ok {
		r0 = returnFunc(par, supplied)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(par, supplied)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPasswordUtil_MakePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakePassword'
type MockIPasswordUtil_MakePassword_Call struct {
	*mock.Call
}

// MakePassword is a helper method to define mock.On call
//   - par int
//   - supplied string
func (_e *MockIPasswordUtil_Expecter) MakePassword(par interface{}, supplied interface{}) *MockIPasswordUtil_MakePassword_Call {
	return &MockIPasswordUtil_MakePassword_Call{Call: _e.mock.On("MakePassword", par, supplied)}
}

func (_c *MockIPasswordUtil_MakePassword_Call) Run(run func(par int, supplied string)) *MockIPasswordUtil_MakePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPasswordUtil_MakePassword_Call) Return(s string, err error) *MockIPasswordUtil_MakePassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIPasswordUtil_MakePassword_Call) RunAndReturn(run func(par int, supplied string) (string, error)) *MockIPasswordUtil_MakePassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITokenUtil creates a new instance of MockITokenUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITokenUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITokenUtil {
	mock := &MockITokenUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITokenUtil is an autogenerated mock type for the ITokenUtil type
type MockITokenUtil struct {
	mock.Mock
}

type MockITokenUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITokenUtil) EXPECT() *MockITokenUtil_Expecter {
	return &MockITokenUtil_Expecter{mock: &_m.Mock}
}

// NewJWT provides a mock function for the type MockITokenUtil
func (_mock *MockITokenUtil) NewJWT(payload jwt.MapClaims, signingKey string, secondsDuration int64) (string, error) {
	ret := _mock.Called(payload, signingKey, secondsDuration)

	if len(ret) == 0 {
		panic("no return value specified for NewJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(jwt.MapClaims, string, int64) (string, error)); ok {
		return returnFunc(payload, signingKey, secondsDuration)
	}
	if returnFunc, ok := ret.Get(0).(func(jwt.MapClaims, string, int64) string); ok {
		r0 = returnFunc(payload, signingKey, secondsDuration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(jwt.MapClaims, string, int64) error); ok {
		r1 = returnFunc(payload, signingKey, secondsDuration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITokenUtil_NewJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewJWT'
type MockITokenUtil_NewJWT_Call struct {
	*mock.Call
}

// NewJWT is a helper method to define mock.On call
//   - payload jwt.MapClaims
//   - signingKey string
//   - secondsDuration int64
func (_e *MockITokenUtil_Expecter) NewJWT(payload interface{}, signingKey interface{}, secondsDuration interface{}) *MockITokenUtil_NewJWT_Call {
	return &MockITokenUtil_NewJWT_Call{Call: _e.mock.On("NewJWT", payload, signingKey, secondsDuration)}
}

func (_c *MockITokenUtil_NewJWT_Call) Run(run func(payload jwt.MapClaims, signingKey string, secondsDuration int64)) *MockITokenUtil_NewJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jwt.MapClaims
		if args[0] != nil {
			arg0 = args[0].(jwt.MapClaims)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITokenUtil_NewJWT_Call) Return(s string, err error) *MockITokenUtil_NewJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockITokenUtil_NewJWT_Call) RunAndReturn(run func(payload jwt.MapClaims, signingKey string, secondsDuration int64) (string, error)) *MockITokenUtil_NewJWT_Call {
	_c.Call.Return(run)
	return _c
}

// ParseJWT provides a mock function for the type MockITokenUtil
func (_mock *MockITokenUtil) ParseJWT(token string, verificationKey string) (jwt.MapClaims, error) {
	ret := _mock.Called(token, verificationKey)

	if len(ret) == 0 {
		panic("no return value specified for ParseJWT")
	}

	var r0 jwt.MapClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (jwt.MapClaims, error)); ok {
		return returnFunc(token, verificationKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) jwt.MapClaims); ok {
		r0 = returnFunc(token, verificationKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(token, verificationKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITokenUtil_ParseJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseJWT'
type MockITokenUtil_ParseJWT_Call struct {
	*mock.Call
}

// ParseJWT is a helper method to define mock.On call
//   - token string
//   - verificationKey string
func (_e *MockITokenUtil_Expecter) ParseJWT(token interface{}, verificationKey interface{}) *MockITokenUtil_ParseJWT_Call {
	return &MockITokenUtil_ParseJWT_Call{Call: _e.mock.On("ParseJWT", token, verificationKey)}
}

func (_c *MockITokenUtil_ParseJWT_Call) Run(run func(token string, verificationKey string)) *MockITokenUtil_ParseJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITokenUtil_ParseJWT_Call) Return(mapClaims jwt.MapClaims, err error) *MockITokenUtil_ParseJWT_Call {
	_c.Call.Return(mapClaims, err)
	return _c
}

func (_c *MockITokenUtil_ParseJWT_Call) RunAndReturn(run func(token string, verificationKey string) (jwt.MapClaims, error)) *MockITokenUtil_ParseJWT_Call {
	_c.Call.Return(run)
	return _c
}
