### ACCOUNT MODULE HTTP TEST
===

===
### Auth END-Point
===
### POST - logged user in
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "secret"
}

### POST - refresh user token
POST http://localhost:8000/api/v1/auth/refresh

### POST - logged user out
POST http://localhost:8000/api/v1/auth/logout

===
### Roles END-Point
===
### GET - fetch list of roles
GET http://localhost:8000/api/v1/roles
Authorization: Bearer "TOKEN_HERE"
accept: application/json

===
### User END-Point
===

### GET - fetch list of users
GET http://localhost:8000/api/v1/users
accept: application/json

### GET - show specified users
GET http://localhost:8000/api/v1/users/1
accept: application/json

### POST - store new user
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "role_id": 1,
  "name": "lorem ipsum",
  "username": "lorem",
  "email": "lorem@ipsum.id",
  "password": "Secret1234@"
}

### PUT - Update specified user
PUT http://localhost:8000/api/v1/users/5
Content-Type: application/json

{
  "role_id": 2,
  "name": "marique ipsum",
  "username": "m_lorem"
}

### DELETE - Destroy specified user
DELETE http://localhost:8000/api/v1/users/5
