// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aasumitro/posbe/internal/model"
	"github.com/aasumitro/posbe/internal/store"
	"github.com/aasumitro/posbe/internal/utils"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIStoreSettingRepository creates a new instance of MockIStoreSettingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStoreSettingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStoreSettingRepository {
	mock := &MockIStoreSettingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStoreSettingRepository is an autogenerated mock type for the IStoreSettingRepository type
type MockIStoreSettingRepository struct {
	mock.Mock
}

type MockIStoreSettingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStoreSettingRepository) EXPECT() *MockIStoreSettingRepository_Expecter {
	return &MockIStoreSettingRepository_Expecter{mock: &_m.Mock}
}

// FindByKey provides a mock function for the type MockIStoreSettingRepository
func (_mock *MockIStoreSettingRepository) FindByKey(ctx context.Context, k string) (*model.StoreSetting, error) {
	ret := _mock.Called(ctx, k)

	if len(ret) == 0 {
		panic("no return value specified for FindByKey")
	}

	var r0 *model.StoreSetting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.StoreSetting, error)); ok {
		return returnFunc(ctx, k)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.StoreSetting); ok {
		r0 = returnFunc(ctx, k)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.StoreSetting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, k)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStoreSettingRepository_FindByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByKey'
type MockIStoreSettingRepository_FindByKey_Call struct {
	*mock.Call
}

// FindByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - k string
func (_e *MockIStoreSettingRepository_Expecter) FindByKey(ctx interface{}, k interface{}) *MockIStoreSettingRepository_FindByKey_Call {
	return &MockIStoreSettingRepository_FindByKey_Call{Call: _e.mock.On("FindByKey", ctx, k)}
}

func (_c *MockIStoreSettingRepository_FindByKey_Call) Run(run func(ctx context.Context, k string)) *MockIStoreSettingRepository_FindByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStoreSettingRepository_FindByKey_Call) Return(storeSetting *model.StoreSetting, err error) *MockIStoreSettingRepository_FindByKey_Call {
	_c.Call.Return(storeSetting, err)
	return _c
}

func (_c *MockIStoreSettingRepository_FindByKey_Call) RunAndReturn(run func(ctx context.Context, k string) (*model.StoreSetting, error)) *MockIStoreSettingRepository_FindByKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockIStoreSettingRepository
func (_mock *MockIStoreSettingRepository) GetAll(ctx context.Context) (*model.StoreSetting, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *model.StoreSetting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.StoreSetting, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.StoreSetting); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.StoreSetting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStoreSettingRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockIStoreSettingRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIStoreSettingRepository_Expecter) GetAll(ctx interface{}) *MockIStoreSettingRepository_GetAll_Call {
	return &MockIStoreSettingRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockIStoreSettingRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockIStoreSettingRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStoreSettingRepository_GetAll_Call) Return(storeSetting *model.StoreSetting, err error) *MockIStoreSettingRepository_GetAll_Call {
	_c.Call.Return(storeSetting, err)
	return _c
}

func (_c *MockIStoreSettingRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) (*model.StoreSetting, error)) *MockIStoreSettingRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIStoreSettingRepository
func (_mock *MockIStoreSettingRepository) Update(ctx context.Context, setting *model.StoreSetting) error {
	ret := _mock.Called(ctx, setting)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.StoreSetting) error); ok {
		r0 = returnFunc(ctx, setting)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStoreSettingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIStoreSettingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - setting *model.StoreSetting
func (_e *MockIStoreSettingRepository_Expecter) Update(ctx interface{}, setting interface{}) *MockIStoreSettingRepository_Update_Call {
	return &MockIStoreSettingRepository_Update_Call{Call: _e.mock.On("Update", ctx, setting)}
}

func (_c *MockIStoreSettingRepository_Update_Call) Run(run func(ctx context.Context, setting *model.StoreSetting)) *MockIStoreSettingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.StoreSetting
		if args[1] != nil {
			arg1 = args[1].(*model.StoreSetting)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStoreSettingRepository_Update_Call) Return(err error) *MockIStoreSettingRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStoreSettingRepository_Update_Call) RunAndReturn(run func(ctx context.Context, setting *model.StoreSetting) error) *MockIStoreSettingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStoreSettingService creates a new instance of MockIStoreSettingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStoreSettingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStoreSettingService {
	mock := &MockIStoreSettingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStoreSettingService is an autogenerated mock type for the IStoreSettingService type
type MockIStoreSettingService struct {
	mock.Mock
}

type MockIStoreSettingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStoreSettingService) EXPECT() *MockIStoreSettingService_Expecter {
	return &MockIStoreSettingService_Expecter{mock: &_m.Mock}
}

// AllSetting provides a mock function for the type MockIStoreSettingService
func (_mock *MockIStoreSettingService) AllSetting(ctx context.Context) (*model.StoreSetting, *utils.ServiceError) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllSetting")
	}

	var r0 *model.StoreSetting
	var r1 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.StoreSetting, *utils.ServiceError)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.StoreSetting); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.StoreSetting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *utils.ServiceError); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.ServiceError)
		}
	}
	return r0, r1
}

// MockIStoreSettingService_AllSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllSetting'
type MockIStoreSettingService_AllSetting_Call struct {
	*mock.Call
}

// AllSetting is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIStoreSettingService_Expecter) AllSetting(ctx interface{}) *MockIStoreSettingService_AllSetting_Call {
	return &MockIStoreSettingService_AllSetting_Call{Call: _e.mock.On("AllSetting", ctx)}
}

func (_c *MockIStoreSettingService_AllSetting_Call) Run(run func(ctx context.Context)) *MockIStoreSettingService_AllSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStoreSettingService_AllSetting_Call) Return(storeSetting *model.StoreSetting, serviceError *utils.ServiceError) *MockIStoreSettingService_AllSetting_Call {
	_c.Call.Return(storeSetting, serviceError)
	return _c
}

func (_c *MockIStoreSettingService_AllSetting_Call) RunAndReturn(run func(ctx context.Context) (*model.StoreSetting, *utils.ServiceError)) *MockIStoreSettingService_AllSetting_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSetting provides a mock function for the type MockIStoreSettingService
func (_mock *MockIStoreSettingService) UpdateSetting(ctx context.Context, form *store.SettingForm) *utils.ServiceError {
	ret := _mock.Called(ctx, form)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSetting")
	}

	var r0 *utils.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *store.SettingForm) *utils.ServiceError); ok {
		r0 = returnFunc(ctx, form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.ServiceError)
		}
	}
	return r0
}

// MockIStoreSettingService_UpdateSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSetting'
type MockIStoreSettingService_UpdateSetting_Call struct {
	*mock.Call
}

// UpdateSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - form *store.SettingForm
func (_e *MockIStoreSettingService_Expecter) UpdateSetting(ctx interface{}, form interface{}) *MockIStoreSettingService_UpdateSetting_Call {
	return &MockIStoreSettingService_UpdateSetting_Call{Call: _e.mock.On("UpdateSetting", ctx, form)}
}

func (_c *MockIStoreSettingService_UpdateSetting_Call) Run(run func(ctx context.Context, form *store.SettingForm)) *MockIStoreSettingService_UpdateSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *store.SettingForm
		if args[1] != nil {
			arg1 = args[1].(*store.SettingForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStoreSettingService_UpdateSetting_Call) Return(serviceError *utils.ServiceError) *MockIStoreSettingService_UpdateSetting_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *MockIStoreSettingService_UpdateSetting_Call) RunAndReturn(run func(ctx context.Context, form *store.SettingForm) *utils.ServiceError) *MockIStoreSettingService_UpdateSetting_Call {
	_c.Call.Return(run)
	return _c
}
