/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SseRouteImport } from './routes/sse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedStoresRouteRouteImport } from './routes/_authenticated/stores/route'
import { Route as AuthenticatedOrdersRouteRouteImport } from './routes/_authenticated/orders/route'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedStoresTransactionsRouteImport } from './routes/_authenticated/stores/transactions'
import { Route as AuthenticatedStoresTeamsRouteImport } from './routes/_authenticated/stores/teams'
import { Route as AuthenticatedStoresCustomersRouteImport } from './routes/_authenticated/stores/customers'
import { Route as AuthenticatedStoresCatalogsRouteImport } from './routes/_authenticated/stores/catalogs'
import { Route as AuthenticatedStoresAttributesRouteImport } from './routes/_authenticated/stores/attributes'
import { Route as AuthenticatedOrdersMenusRouteImport } from './routes/_authenticated/orders/menus'
import { Route as AuthenticatedOrdersFloorsRouteImport } from './routes/_authenticated/orders/floors'

const AuthenticatedIndexLazyRouteImport = createFileRoute('/_authenticated/')()
const AuthenticatedStoresIndexLazyRouteImport = createFileRoute(
  '/_authenticated/stores/',
)()
const AuthenticatedStoresFloorsLazyRouteImport = createFileRoute(
  '/_authenticated/stores/floors',
)()
const AuthenticatedStoresProductsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/stores/products/',
)()
const AuthenticatedStoresProductsIdLazyRouteImport = createFileRoute(
  '/_authenticated/stores/products/$id',
)()

const SseRoute = SseRouteImport.update({
  id: '/sse',
  path: '/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)
const AuthenticatedStoresRouteRoute =
  AuthenticatedStoresRouteRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRouteRoute =
  AuthenticatedOrdersRouteRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresIndexLazyRoute =
  AuthenticatedStoresIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/stores/index.lazy').then((d) => d.Route),
  )
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrdersRouteRoute,
  } as any)
const AuthenticatedStoresFloorsLazyRoute =
  AuthenticatedStoresFloorsLazyRouteImport.update({
    id: '/floors',
    path: '/floors',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/stores/floors.lazy').then((d) => d.Route),
  )
const AuthenticatedStoresTransactionsRoute =
  AuthenticatedStoresTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any)
const AuthenticatedStoresTeamsRoute =
  AuthenticatedStoresTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any)
const AuthenticatedStoresCustomersRoute =
  AuthenticatedStoresCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any)
const AuthenticatedStoresCatalogsRoute =
  AuthenticatedStoresCatalogsRouteImport.update({
    id: '/catalogs',
    path: '/catalogs',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any)
const AuthenticatedStoresAttributesRoute =
  AuthenticatedStoresAttributesRouteImport.update({
    id: '/attributes',
    path: '/attributes',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any)
const AuthenticatedOrdersMenusRoute =
  AuthenticatedOrdersMenusRouteImport.update({
    id: '/menus',
    path: '/menus',
    getParentRoute: () => AuthenticatedOrdersRouteRoute,
  } as any)
const AuthenticatedOrdersFloorsRoute =
  AuthenticatedOrdersFloorsRouteImport.update({
    id: '/floors',
    path: '/floors',
    getParentRoute: () => AuthenticatedOrdersRouteRoute,
  } as any)
const AuthenticatedStoresProductsIndexLazyRoute =
  AuthenticatedStoresProductsIndexLazyRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/stores/products/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedStoresProductsIdLazyRoute =
  AuthenticatedStoresProductsIdLazyRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedStoresRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/stores/products/$id.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/sse': typeof SseRoute
  '/orders': typeof AuthenticatedOrdersRouteRouteWithChildren
  '/stores': typeof AuthenticatedStoresRouteRouteWithChildren
  '/': typeof AuthenticatedIndexLazyRoute
  '/orders/floors': typeof AuthenticatedOrdersFloorsRoute
  '/orders/menus': typeof AuthenticatedOrdersMenusRoute
  '/stores/attributes': typeof AuthenticatedStoresAttributesRoute
  '/stores/catalogs': typeof AuthenticatedStoresCatalogsRoute
  '/stores/customers': typeof AuthenticatedStoresCustomersRoute
  '/stores/teams': typeof AuthenticatedStoresTeamsRoute
  '/stores/transactions': typeof AuthenticatedStoresTransactionsRoute
  '/stores/floors': typeof AuthenticatedStoresFloorsLazyRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/stores/': typeof AuthenticatedStoresIndexLazyRoute
  '/stores/products/$id': typeof AuthenticatedStoresProductsIdLazyRoute
  '/stores/products': typeof AuthenticatedStoresProductsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sse': typeof SseRoute
  '/': typeof AuthenticatedIndexLazyRoute
  '/orders/floors': typeof AuthenticatedOrdersFloorsRoute
  '/orders/menus': typeof AuthenticatedOrdersMenusRoute
  '/stores/attributes': typeof AuthenticatedStoresAttributesRoute
  '/stores/catalogs': typeof AuthenticatedStoresCatalogsRoute
  '/stores/customers': typeof AuthenticatedStoresCustomersRoute
  '/stores/teams': typeof AuthenticatedStoresTeamsRoute
  '/stores/transactions': typeof AuthenticatedStoresTransactionsRoute
  '/stores/floors': typeof AuthenticatedStoresFloorsLazyRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/stores': typeof AuthenticatedStoresIndexLazyRoute
  '/stores/products/$id': typeof AuthenticatedStoresProductsIdLazyRoute
  '/stores/products': typeof AuthenticatedStoresProductsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sse': typeof SseRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteRouteWithChildren
  '/_authenticated/stores': typeof AuthenticatedStoresRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexLazyRoute
  '/_authenticated/orders/floors': typeof AuthenticatedOrdersFloorsRoute
  '/_authenticated/orders/menus': typeof AuthenticatedOrdersMenusRoute
  '/_authenticated/stores/attributes': typeof AuthenticatedStoresAttributesRoute
  '/_authenticated/stores/catalogs': typeof AuthenticatedStoresCatalogsRoute
  '/_authenticated/stores/customers': typeof AuthenticatedStoresCustomersRoute
  '/_authenticated/stores/teams': typeof AuthenticatedStoresTeamsRoute
  '/_authenticated/stores/transactions': typeof AuthenticatedStoresTransactionsRoute
  '/_authenticated/stores/floors': typeof AuthenticatedStoresFloorsLazyRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/stores/': typeof AuthenticatedStoresIndexLazyRoute
  '/_authenticated/stores/products/$id': typeof AuthenticatedStoresProductsIdLazyRoute
  '/_authenticated/stores/products/': typeof AuthenticatedStoresProductsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/sse'
    | '/orders'
    | '/stores'
    | '/'
    | '/orders/floors'
    | '/orders/menus'
    | '/stores/attributes'
    | '/stores/catalogs'
    | '/stores/customers'
    | '/stores/teams'
    | '/stores/transactions'
    | '/stores/floors'
    | '/orders/'
    | '/stores/'
    | '/stores/products/$id'
    | '/stores/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sse'
    | '/'
    | '/orders/floors'
    | '/orders/menus'
    | '/stores/attributes'
    | '/stores/catalogs'
    | '/stores/customers'
    | '/stores/teams'
    | '/stores/transactions'
    | '/stores/floors'
    | '/orders'
    | '/stores'
    | '/stores/products/$id'
    | '/stores/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/sse'
    | '/_authenticated/orders'
    | '/_authenticated/stores'
    | '/_authenticated/'
    | '/_authenticated/orders/floors'
    | '/_authenticated/orders/menus'
    | '/_authenticated/stores/attributes'
    | '/_authenticated/stores/catalogs'
    | '/_authenticated/stores/customers'
    | '/_authenticated/stores/teams'
    | '/_authenticated/stores/transactions'
    | '/_authenticated/stores/floors'
    | '/_authenticated/orders/'
    | '/_authenticated/stores/'
    | '/_authenticated/stores/products/$id'
    | '/_authenticated/stores/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SseRoute: typeof SseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sse': {
      id: '/sse'
      path: '/sse'
      fullPath: '/sse'
      preLoaderRoute: typeof SseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/': {
      id: '/_authenticated/stores/'
      path: '/'
      fullPath: '/stores/'
      preLoaderRoute: typeof AuthenticatedStoresIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedOrdersRouteRoute
    }
    '/_authenticated/stores/floors': {
      id: '/_authenticated/stores/floors'
      path: '/floors'
      fullPath: '/stores/floors'
      preLoaderRoute: typeof AuthenticatedStoresFloorsLazyRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
    '/_authenticated/stores/transactions': {
      id: '/_authenticated/stores/transactions'
      path: '/transactions'
      fullPath: '/stores/transactions'
      preLoaderRoute: typeof AuthenticatedStoresTransactionsRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
    '/_authenticated/stores/teams': {
      id: '/_authenticated/stores/teams'
      path: '/teams'
      fullPath: '/stores/teams'
      preLoaderRoute: typeof AuthenticatedStoresTeamsRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
    '/_authenticated/stores/customers': {
      id: '/_authenticated/stores/customers'
      path: '/customers'
      fullPath: '/stores/customers'
      preLoaderRoute: typeof AuthenticatedStoresCustomersRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
    '/_authenticated/stores/catalogs': {
      id: '/_authenticated/stores/catalogs'
      path: '/catalogs'
      fullPath: '/stores/catalogs'
      preLoaderRoute: typeof AuthenticatedStoresCatalogsRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
    '/_authenticated/stores/attributes': {
      id: '/_authenticated/stores/attributes'
      path: '/attributes'
      fullPath: '/stores/attributes'
      preLoaderRoute: typeof AuthenticatedStoresAttributesRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
    '/_authenticated/orders/menus': {
      id: '/_authenticated/orders/menus'
      path: '/menus'
      fullPath: '/orders/menus'
      preLoaderRoute: typeof AuthenticatedOrdersMenusRouteImport
      parentRoute: typeof AuthenticatedOrdersRouteRoute
    }
    '/_authenticated/orders/floors': {
      id: '/_authenticated/orders/floors'
      path: '/floors'
      fullPath: '/orders/floors'
      preLoaderRoute: typeof AuthenticatedOrdersFloorsRouteImport
      parentRoute: typeof AuthenticatedOrdersRouteRoute
    }
    '/_authenticated/stores/products/': {
      id: '/_authenticated/stores/products/'
      path: '/products'
      fullPath: '/stores/products'
      preLoaderRoute: typeof AuthenticatedStoresProductsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
    '/_authenticated/stores/products/$id': {
      id: '/_authenticated/stores/products/$id'
      path: '/products/$id'
      fullPath: '/stores/products/$id'
      preLoaderRoute: typeof AuthenticatedStoresProductsIdLazyRouteImport
      parentRoute: typeof AuthenticatedStoresRouteRoute
    }
  }
}

interface AuthenticatedOrdersRouteRouteChildren {
  AuthenticatedOrdersFloorsRoute: typeof AuthenticatedOrdersFloorsRoute
  AuthenticatedOrdersMenusRoute: typeof AuthenticatedOrdersMenusRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedOrdersRouteRouteChildren: AuthenticatedOrdersRouteRouteChildren =
  {
    AuthenticatedOrdersFloorsRoute: AuthenticatedOrdersFloorsRoute,
    AuthenticatedOrdersMenusRoute: AuthenticatedOrdersMenusRoute,
    AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  }

const AuthenticatedOrdersRouteRouteWithChildren =
  AuthenticatedOrdersRouteRoute._addFileChildren(
    AuthenticatedOrdersRouteRouteChildren,
  )

interface AuthenticatedStoresRouteRouteChildren {
  AuthenticatedStoresAttributesRoute: typeof AuthenticatedStoresAttributesRoute
  AuthenticatedStoresCatalogsRoute: typeof AuthenticatedStoresCatalogsRoute
  AuthenticatedStoresCustomersRoute: typeof AuthenticatedStoresCustomersRoute
  AuthenticatedStoresTeamsRoute: typeof AuthenticatedStoresTeamsRoute
  AuthenticatedStoresTransactionsRoute: typeof AuthenticatedStoresTransactionsRoute
  AuthenticatedStoresFloorsLazyRoute: typeof AuthenticatedStoresFloorsLazyRoute
  AuthenticatedStoresIndexLazyRoute: typeof AuthenticatedStoresIndexLazyRoute
  AuthenticatedStoresProductsIdLazyRoute: typeof AuthenticatedStoresProductsIdLazyRoute
  AuthenticatedStoresProductsIndexLazyRoute: typeof AuthenticatedStoresProductsIndexLazyRoute
}

const AuthenticatedStoresRouteRouteChildren: AuthenticatedStoresRouteRouteChildren =
  {
    AuthenticatedStoresAttributesRoute: AuthenticatedStoresAttributesRoute,
    AuthenticatedStoresCatalogsRoute: AuthenticatedStoresCatalogsRoute,
    AuthenticatedStoresCustomersRoute: AuthenticatedStoresCustomersRoute,
    AuthenticatedStoresTeamsRoute: AuthenticatedStoresTeamsRoute,
    AuthenticatedStoresTransactionsRoute: AuthenticatedStoresTransactionsRoute,
    AuthenticatedStoresFloorsLazyRoute: AuthenticatedStoresFloorsLazyRoute,
    AuthenticatedStoresIndexLazyRoute: AuthenticatedStoresIndexLazyRoute,
    AuthenticatedStoresProductsIdLazyRoute:
      AuthenticatedStoresProductsIdLazyRoute,
    AuthenticatedStoresProductsIndexLazyRoute:
      AuthenticatedStoresProductsIndexLazyRoute,
  }

const AuthenticatedStoresRouteRouteWithChildren =
  AuthenticatedStoresRouteRoute._addFileChildren(
    AuthenticatedStoresRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrdersRouteRoute: typeof AuthenticatedOrdersRouteRouteWithChildren
  AuthenticatedStoresRouteRoute: typeof AuthenticatedStoresRouteRouteWithChildren
  AuthenticatedIndexLazyRoute: typeof AuthenticatedIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrdersRouteRoute: AuthenticatedOrdersRouteRouteWithChildren,
  AuthenticatedStoresRouteRoute: AuthenticatedStoresRouteRouteWithChildren,
  AuthenticatedIndexLazyRoute: AuthenticatedIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SseRoute: SseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
